name: Android Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Add sdkmanager to PATH
        run: echo "/usr/local/lib/android/sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Install CMake 3.22.1
        run: sdkmanager --install "cmake;3.22.1"

      - name: Configure CMake dir
        run: echo "cmake.dir=/usr/local/lib/android/sdk/cmake/3.22.1" >> android/gradle.properties

      - name: Decrypt Keystore
        run: |
          echo "$TOM_SP_KEYSTORE_BASE64" | base64 --decode > android/app/tom-SP.keystore
        env:
          TOM_SP_KEYSTORE_BASE64: ${{ secrets.TOM_SP_KEYSTORE_BASE64 }}

      - name: Set up signing properties
        run: |
          echo "MYAPP_UPLOAD_STORE_FILE=tom-SP.keystore" >> android/gradle.properties
          echo "MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.MY_KEY_ALIAS }}" >> android/gradle.properties
          echo "MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.MY_KEYSTORE_PASSWORD }}" >> android/gradle.properties
          echo "MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.MY_KEY_PASSWORD }}" >> android/gradle.properties
        env:
          MY_KEY_ALIAS: ${{ secrets.MY_KEY_ALIAS }}
          MY_KEYSTORE_PASSWORD: ${{ secrets.MY_KEYSTORE_PASSWORD }}
          MY_KEY_PASSWORD: ${{ secrets.MY_KEY_PASSWORD }}

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # 1) Generamos una variable de entorno con la fecha YYYYMMDD (UTC del runner)
      - name: Set build date
        run: echo "BUILD_DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV

      # 2) Compilamos el APK
      - name: Build Release APK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      # 3) Renombramos el APK usando la fecha
      - name: Rename APK to include date
        run: |
          mv android/app/build/outputs/apk/release/app-release.apk \
             android/app/build/outputs/apk/release/KRN42_${{ env.BUILD_DATE }}.apk

      # 4) Lo subimos por FTP con el nuevo nombre
      - name: Deploy APK via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: android/app/build/outputs/apk/release/   # carpeta con slash al final 
          server-dir: /public_html/downloads/
          include: KRN42_${{ env.BUILD_DATE }}.apk
