name: Android Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Add sdkmanager to PATH
        run: echo "/usr/local/lib/android/sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Install CMake 3.22.1
        run: sdkmanager --install "cmake;3.22.1"

      - name: Configure CMake dir
        run: echo "cmake.dir=/usr/local/lib/android/sdk/cmake/3.22.1" >> android/gradle.properties

      - name: Decrypt Keystore
        run: |
          echo "$TOM_SP_KEYSTORE_BASE64" | base64 --decode > android/app/tom-SP.keystore
        env:
          TOM_SP_KEYSTORE_BASE64: ${{ secrets.TOM_SP_KEYSTORE_BASE64 }}

      - name: Set up signing properties
        run: |
          echo "MYAPP_UPLOAD_STORE_FILE=tom-SP.keystore" >> android/gradle.properties
          echo "MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.MY_KEY_ALIAS }}" >> android/gradle.properties
          echo "MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.MY_KEYSTORE_PASSWORD }}" >> android/gradle.properties
          echo "MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.MY_KEY_PASSWORD }}" >> android/gradle.properties
        env:
          MY_KEY_ALIAS: ${{ secrets.MY_KEY_ALIAS }}
          MY_KEYSTORE_PASSWORD: ${{ secrets.MY_KEYSTORE_PASSWORD }}
          MY_KEY_PASSWORD: ${{ secrets.MY_KEY_PASSWORD }}

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Build Release APK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Deploy APK via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}        # por ejemplo: ftp.midominio.com
          username: ${{ secrets.FTP_USERNAME }}    # tu usuario FTP
          password: ${{ secrets.FTP_PASSWORD }}    # tu contraseña FTP
          local-dir: android/app/build/outputs/apk/release/
          server-dir: /public_html/downloads/        # ajusta según carpeta destino en tu servidor
          include: app-release.apk                  # solo este archivo se sube
